/** Example Spotify playlists — PlaylistSpotifyUriExample in Flutter. */
export const EXAMPLE_PLAYLISTS: { type: string; uri: string; name: string }[] = [
  { type: "hotspot", uri: "playlist/7w2SzKpEX07q2ormj6aDFi", name: "Score Hjemme 1" },
  { type: "hotspot", uri: "playlist/6fJXMdlIVFtbcHBFeViWqr", name: "Score Hjemme 2" },
  { type: "hotspot", uri: "playlist/3bPnAnhr5i5CZhVWhjcvqN", name: "Score Borte" },
  { type: "hotspot", uri: "playlist/3CowNHNZXYom1JqwdFHQal", name: "Chill 2" },
  { type: "hotspot", uri: "playlist/1pbQjl2mNrIzBBqZKTgqQ7", name: "Pump It Up!" },
  { type: "match", uri: "playlist/3s93nj36LDDHzz0njr5P3t", name: "Funk Off" },
  { type: "funStuff", uri: "playlist/2ICHHgcQVkxfz6BnaRfEjD", name: "Intervensjon" },
  { type: "hotspot", uri: "playlist:5THsvdwlxPboeXPnMCqaYH", name: "" },
  { type: "hotspot", uri: "playlist/1xzEllVUTnZm70xn4zlMkv", name: "" },
  { type: "match", uri: "playlist:2QsZRdF8n8JbZGJmheuTvt", name: "" },
  { type: "match", uri: "playlist/1BwYcCSsMbL7U38kWU3TE8", name: "" },
  { type: "funStuff", uri: "playlist/1NiUvxz1hjHth95BoIhpmx", name: "" },
  { type: "funStuff", uri: "playlist/7tBoxilzbBtO5rFoErMBhr", name: "" },
  { type: "funStuff", uri: "playlist/22GBDyfNMlTGmj6uTOst7P", name: "" },
  { type: "funStuff", uri: "playlist:11J7lwyg9AOB2cGeYLZ8o8", name: "" },
  { type: "funStuff", uri: "playlist/2lf6ls1KOYLww3Qqj6oP99", name: "" },
  { type: "preMatch", uri: "playlist/0rMJYwKMTY9qZ3rAnOiYUN", name: "" },
  { type: "preMatch", uri: "playlist/0tJ9cHK1AqMz4Hz0KKjFfT", name: "" },
  { type: "preMatch", uri: "playlist/5npiOA4OTXZc3JZMEeb6tr", name: "" },
  { type: "preMatch", uri: "playlist/4FZ1ewVjhSDq6Wvb1zHK4C", name: "" },
  { type: "preMatch", uri: "playlist/5FndZkkown4QwMFC4KwsCq", name: "" },
  { type: "preMatch", uri: "playlist:2gTKxeQWfajAzIdlNEUJBc", name: "" },
  { type: "preMatch", uri: "playlist:0RPNCAg3M3NtoFIU4QoU30", name: "" },
];
